#!/bin/sh
#
# This preprocesses a set of word lists into a suitable form for input
# into cracklib-packer
#
# removed this, cause it seems like the database should also include special chars and symbols for optimum results
#    tr -cd '\012[a-z][0-9]' |
#
gzip -cdf $* |
    tr '[A-Z]' '[a-z]' |
    sort |
    uniq |
    grep -v '^#' |
    grep -v '^$'
