.TH update\-cracklib 8 "June 09, 2003" "Martin Pitt"
.SH NAME
update\-cracklib \- Regenerate cracklib dictionary
.SH SYNOPSIS
.B update\-cracklib
.br

.SH DESCRIPTION
.B update\-cracklib
builds a compressed and accumulated version of wordlists stored in the
directories given in cracklib's configuration file
/etc/cracklib/cracklib.conf. Programs using cracklib2 need this
database to be of any use.
.PP
By default this script is called by cron every day.

.SH RESULT
.B
update\-cracklib
prints out two numbers: the number of words read from the ASCII
dictionaries and the number of words eventually written into the
cracklib database; if no error occurred, these should be equal.
.PP
0 is returned on success, otherwise an error message is printed to 
standard error and \-1 is returned.

.SH FILES
.TP
.B /etc/cracklib/cracklib.conf
shell script that sets 
.B
cracklib_dictpath_src
which must be a space separated list of source dictionary files.

.SH SEE ALSO
.BR cracklib (3),
.BR crack_mkdict (8)

.SH AUTHOR
This program and manual page was written by Martin Pitt
<martin@piware.de> for the Debian GNU/Linux System (but may be used by
others).

